<?php
/**
 * Sirv manually added assets block template
 *
 * @author    Sirv Limited <support@sirv.com>
 * @copyright Copyright (c) 2018-2023 Sirv Limited <support@sirv.com>. All rights reserved
 * @license   https://sirv.com/
 * @link      https://sirv.com/integration/magento/
 *
 * @codingStandardsIgnoreFile
 */

// @codingStandardsIgnoreFile

/** @var $block \Sirv\Magento2\Block\Adminhtml\Product\Edit\SirvAssets\ManuallyAdded\Content */

$elementName = $block->getElement()->getName();
$formName = $block->getFormName();
$productId = $block->getElement()->getProductId();

?>
<div id="<?= $block->getHtmlId() ?>"
     class="gallery sirv-manually-added-assets"
     data-mage-init='{"sirvManuallyAddedAssets":{"template":"#<?= $block->getHtmlId() ?>-template"}}'
     data-parent-component="<?= $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-asset-picker-config="<?= $block->escapeHtml($block->getAssetPickerConfigJson()) ?>"
     data-product-id="<?= $block->escapeHtml($productId) ?>"
     data-images="<?= $block->escapeHtml($block->getAssetsJson()) ?>"
    >
    <?php if (!$block->getElement()->getReadonly()) { ?>
        <div class="image image-placeholder action-add-item">
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= /* @escapeNotVerified */ __('Add from Sirv'); ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <script id="<?= $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item" data-role="sirv-asset">
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][position]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.position %>"
                   class="position"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][file]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.file %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][id]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.id %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value=""
                   class="is-removed"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][name]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.name %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][type]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.type %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][width]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.width %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][height]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.height %>"/>
            <input type="hidden"
                   name="<?= /* @escapeNotVerified */ $elementName ?>[<%- data.file_id %>][size]"
                   data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
                   value="<%- data.size %>"/>

            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.file %>"
                     title="<%- data.file %>"/>

                <div class="actions">
                    <div class="tooltip">
                        <span class="delete-tooltiptext">
                            <?= $block->escapeHtml(__('Remove')) ?>
                        </span>
                        <button type="button"
                                class="action-remove"
                                data-role="delete-button">
                            <span>
                                <?= $block->escapeHtml(__('Remove')) ?>
                            </span>
                        </button>
                    </div>
                    <div class="draggable-handle"></div>
                </div>
            </div>

            <div class="item-description">
                <div class="item-size">
                  <span data-role="image-dimens-wrapper"><span data-role="image-dimens"></span>, </span><span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>
        </div>
    </script>
    <?= $block->getUploaderHtml(); ?>
</div>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
