<?php
/**
 * Gallery block template
 *
 * @author    Sirv Limited <support@sirv.com>
 * @copyright Copyright (c) 2018-2023 Sirv Limited <support@sirv.com>. All rights reserved
 * @license   https://sirv.com/
 * @link      https://sirv.com/integration/magento/
 *
 * @codingStandardsIgnoreFile
 */

/**
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$viewerHelper = $objectManager->get(\Sirv\Magento2\Helper\MediaViewer::class);
$viewerHelper->setGalleryBlock($block);

$viewerSlides = $viewerHelper->getViewerSlides();
$usePlaceholder = $viewerHelper->usePlaceholder();
$placeholder = $viewerHelper->getPlaceholder();
if (empty($placeholder['url'])) {
    $placeholder['url'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAQAAADa613fAAAAaElEQVR42u3PQREAAAwCoNm/9CL496ABuREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREWkezG8AZQ6nfncAAAAASUVORK5CYII=';
}
$jsonConfig = $block->escapeHtmlAttr($viewerHelper->getJsonConfig());
$jsOptions = $viewerHelper->getViewerJsOptions();

$isThumbsLayoutH = true;
if (preg_match('#\bposition\s*+:\s*+("|\')(bottom|left|right|top)\1#', $jsOptions, $match)) {
    if (in_array($match[2], ['left', 'right'])) {
        $isThumbsLayoutH = false;
    }
}

$thumbSize = 70;
if (preg_match('#\bsize\s*+:\s*+(\d++)#', $jsOptions, $match)) {
    $thumbSize = $match[1];
}

$maxHeight = $viewerHelper->getMaxHeight();
$customCss = $viewerHelper->getViewerCss();
$dataOptions = $viewerHelper->getViewerDataOptions();
$assetsCacheData = $viewerHelper->getAssetsCacheData();
?>
<?= /* @noEscape */ $jsOptions ?>
<style>
.smv-pg-container {
    width: 100%;
}
<?php if ($maxHeight) : ?>
.smv-pg-container .Sirv {
    min-height: 1px;
}
.smv-pg-container .pdp-gallery-main,
.smv-pg-container .pdp-gallery-placeholder,
.smv-pg-container .Sirv > .smv {
    max-height: <?= /* @noEscape */ $maxHeight ?>px;
}
<?php endif; ?>
.pdp-gallery-thumbnails {
    <?= /* @noEscape */ ($isThumbsLayoutH ? 'height' : 'width') . ': ' . $thumbSize . 'px;' ?>
}
<?= /* @noEscape */ $customCss ?>
</style>
<?php if ($usePlaceholder) : ?>
<div class="smv-pg-container" data-json-config="<?= /* @noEscape */ $jsonConfig ?>" data-mage-init='{"sirvAssetsCache":<?= /* @noEscape */ $assetsCacheData ?>}'>
    <div class="pdp-gallery-container<?= /* @noEscape */ $isThumbsLayoutH ? ' pdp-gallery-container-h' : '' ?>">
        <div class="pdp-gallery-thumbnails"></div>
        <div class="pdp-gallery-main">
            <img width="<?= /* @noEscape */ $placeholder['width'] ?>" height="<?= /* @noEscape */ $placeholder['height'] ?>" class="pdp-gallery-placeholder" src="<?= /* @noEscape */ $placeholder['url'] ?>" alt="" loading="lazy">
            <div class="Sirv mainimage" data-options="<?= /* @noEscape */ $dataOptions ?>">
                <?= /* @noEscape */ implode("\n", $viewerSlides) ?>
            </div>
        </div>
    </div>
</div>
<?php else : ?>
<div class="smv-pg-container" data-json-config="<?= /* @noEscape */ $jsonConfig ?>" data-mage-init='{"sirvAssetsCache":<?= /* @noEscape */ $assetsCacheData ?>}'>
    <div class="Sirv" data-options="<?= /* @noEscape */ $dataOptions ?>">
        <?= /* @noEscape */ implode("\n", $viewerSlides) ?>
    </div>
</div>
<?php endif; ?>
