<?php
/**
 * Gallery block template
 *
 * @author    Sirv Limited <support@sirv.com>
 * @copyright Copyright (c) 2018-2020 Sirv Limited <support@sirv.com>. All rights reserved
 * @license   https://sirv.com/
 * @link      https://sirv.com/integration/magento/
 *
 * @codingStandardsIgnoreFile
 */

/**
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$viewerHelper = $objectManager->get(\MagicToolbox\Sirv\Helper\MediaViewer::class);
$viewerHelper->setGalleryBlock($block);

$viewerSlides = $viewerHelper->getViewerSlides();
$ids = $block->escapeHtmlAttr(json_encode(array_keys($viewerSlides)));
?>
<div class="smv-pg-container" data-initial-slides="<?= $ids ?>">
    <div class="Sirv" data-options="<?= $viewerHelper->getViewerOptions() ?>">
        <?= implode("\n", $viewerSlides) ?>
    </div>
</div>
