<?php
/**
 * Form after template
 *
 * @author    Sirv Limited <support@sirv.com>
 * @copyright Copyright (c) 2018-2020 Sirv Limited <support@sirv.com>. All rights reserved
 * @license   https://sirv.com/
 * @link      https://sirv.com/integration/magento/
 *
 * @codingStandardsIgnoreFile
 */

/* @var $block \Magento\Framework\View\Element\Template */
?>
<script type="text/x-magento-init">
    {
        "#edit_form": {
            "MagicToolbox_Sirv/js/form-helper": {}
        },
        "[data-role=scope-switcher]": {
            "MagicToolbox_Sirv/js/scope-switcher": {}
        }
    }
</script>
