<?php
/**
 * Version block template
 *
 * @author    Sirv Limited <support@sirv.com>
 * @copyright Copyright (c) 2018-2021 Sirv Limited <support@sirv.com>. All rights reserved
 * @license   https://sirv.com/
 * @link      https://sirv.com/integration/magento/
 *
 * @codingStandardsIgnoreFile
 */

/**
 * @var $block \Sirv\Magento2\Block\Adminhtml\Version
 */

$changelogUrl = $block->escapeUrl($block->getChangelogUrl());
?>
<div class="mt-module-version">
    <span class="mt-current-version">
        <a href="#" data-mage-init='{"sirvChangelog":{"changelogUrl":"<?= $changelogUrl; ?>"}}'>
            Version: <?= $block->getCurrentVersion() ?>
        </a>
    </span>
</div>
